apiVersion: v1
kind: Service
metadata:
  name: istio-state-metrics
  namespace: istio-system
  labels:
    app: istio-state-metrics
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: http-metrics
    port: 9090
    targetPort: http-metrics
    protocol: TCP
  selector:
    app: istio-state-metrics
