apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-state-metrics
rules:
- apiGroups: ["config.istio.io"]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: ["networking.istio.io"]
  resources: ["*"]
  verbs: ["list", "watch"]